### ISSUE TITLE
New ESPHome version - new problems.

### ISSUE THREAD

**Issue by victordk** [nic6911/ESP32_Modbus_Module#24]
When trying to compile with ESPHome 2026.3.0 i get the following error in the build log.

``
Compiling .pioenvs/wavin/esp-tls/esp_tls_error_capture.c.o
src/main.cpp: In function 'void setup()':
src/main.cpp:428:21: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  428 |   sensor_sensor_id->set_device_class("battery");
      |                     ^~~~~~~~~~~~~~~~
      |                     get_device_class
src/main.cpp:429:21: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  429 |   sensor_sensor_id->set_unit_of_measurement("%");
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                     get_unit_of_measurement
src/main.cpp:430:21: error: 'class esphome::sensor::Sensor' has no member named 'set_icon'; did you mean 'get_icon'?
  430 |   sensor_sensor_id->set_icon("mdi:battery");
      |                     ^~~~~~~~
      |                     get_icon
src/main.cpp:446:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  446 |   sensor_sensor_id_2->set_device_class("temperature");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:447:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  447 |   sensor_sensor_id_2->set_unit_of_measurement("\302\260C");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:463:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  463 |   sensor_sensor_id_3->set_device_class("battery");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:464:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  464 |   sensor_sensor_id_3->set_unit_of_measurement("%");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:465:23: error: 'class esphome::sensor::Sensor' has no member named 'set_icon'; did you mean 'get_icon'?
  465 |   sensor_sensor_id_3->set_icon("mdi:battery");
      |                       ^~~~~~~~
      |                       get_icon
src/main.cpp:481:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  481 |   sensor_sensor_id_4->set_device_class("temperature");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:482:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  482 |   sensor_sensor_id_4->set_unit_of_measurement("\302\260C");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:498:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  498 |   sensor_sensor_id_5->set_device_class("battery");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:499:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  499 |   sensor_sensor_id_5->set_unit_of_measurement("%");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:500:23: error: 'class esphome::sensor::Sensor' has no member named 'set_icon'; did you mean 'get_icon'?
  500 |   sensor_sensor_id_5->set_icon("mdi:battery");
      |                       ^~~~~~~~
      |                       get_icon
src/main.cpp:516:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  516 |   sensor_sensor_id_6->set_device_class("temperature");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:517:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  517 |   sensor_sensor_id_6->set_unit_of_measurement("\302\260C");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:533:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  533 |   sensor_sensor_id_7->set_device_class("battery");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:534:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  534 |   sensor_sensor_id_7->set_unit_of_measurement("%");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
src/main.cpp:535:23: error: 'class esphome::sensor::Sensor' has no member named 'set_icon'; did you mean 'get_icon'?
  535 |   sensor_sensor_id_7->set_icon("mdi:battery");
      |                       ^~~~~~~~
      |                       get_icon
src/main.cpp:551:23: error: 'class esphome::sensor::Sensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
  551 |   sensor_sensor_id_8->set_device_class("temperature");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/main.cpp:552:23: error: 'class esphome::sensor::Sensor' has no member named 'set_unit_of_measurement'; did you mean 'get_unit_of_measurement'?
  552 |   sensor_sensor_id_8->set_unit_of_measurement("\302\260C");
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
      |                       get_unit_of_measurement
Compiling .pioenvs/wavin/esp-tls/esp_tls_platform_port.c.o
Compiling .pioenvs/wavin/esp-tls/esp_tls_mbedtls.c.o
*** [.pioenvs/wavin/src/main.cpp.o] Error 1
========================== [FAILED] Took 4.64 seconds ==========================
``

Yaml configuration:
`
########################################################################################
#                                                                                      #
#      WAVIN AHC-9000 FLOOR HEATING CONTROLLER SOFTWARE FOR HOME ASSISTANT             #
#                                                                                      #   
#        Code developed by : Heine Koldbro Madsen and Samuel Sieb 2021                 #
#                                                                                      #
#           https://github.com/heinekmadsen/esphome_wavinahc9000v3/tree/main           #    
#                                                                                      #
# Hardware by : Mogens Groth Nicolaisen https://github.com/nic6911/Wavin-AHC-9000-mqtt #
#                                                                                      #
########################################################################################
 
esphome:
  name: wavin
  friendly_name: Wavin

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_components
    components: [wavinahc9000v3]
    refresh: 0s

logger:
  baud_rate: 0

uart:
  id: uart_wavin
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavinahc9000v3:
  id: wavin
  uart_id: uart_wavin
  update_interval: 10s
  poll_channels_per_cycle: 1
  allow_mode_writes: true
  flow_control_pin: GPIO10
 
  channel_01_friendly_name: "Clara"
  channel_02_friendly_name: "Freja"
  channel_03_friendly_name: "Badeværelse"
  channel_04_friendly_name: "Gang"

climate:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Clara"
    channel: 1
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Freja"
    channel: 2
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Badevaerelse"
    channel: 3
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Gang"
    channel: 4
sensor:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Clara Battery"
    channel: 1
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Clara Temperature"
    channel: 1
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Freja Battery"
    channel: 2
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Freja Temperature"
    channel: 2
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Badevaerelse Battery"
    channel: 3
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Badevaerelse Temperature"
    channel: 3
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Gang Battery"
    channel: 4
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Gang Temperature"
    channel: 4
    type: temperature
  #

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: ""

ota:
  platform: `esphome`
``

**Comment by nic6911** [comment]
Fixed - please try compiling again now

**Comment by victordk** [comment]
Works fine now - thx.
